IP2-452 - database schema
intive/patronage21-java-student-record pull request #2
Opened 2021-06-17 10:47 UTC by lzolkiewski

2021-06-23 15:45 UTC, kari565 commented on src/main/resources/db/migration/V1_0_1__initial_data.sql
> +INSERT INTO technology_group(id, name) VALUES(NEXTVAL('status_seq'), 'Android');
W module użytkownika mamy grupe Mobile (Android) zamiast Android.

2021-06-24 12:30 UTC, patronage-java-leaders-2021 requested changes

2021-06-24 12:30 UTC, patronage-java-leaders-2021 commented on build.gradle
> +    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-validation', version: '2.4.3'
Starajmy się trzymać jednej konwencji zapisu zależności. W projekcie przyjeliśmy że jest to string, więc trzymajmy się konwencji. Proszę o zmianę. Dziękuję.

2021-06-24 12:50 UTC, patronage-java-leaders-2021 approved these changes

2021-06-24 13:03 UTC, kari565 approved these changes

2021-06-24 13:07 UTC, merged