IP2-447 - integrate data with user module
intive/patronage21-java-student-record pull request #6
Opened 2021-06-25 10:33 UTC by kari565

2021-06-25 13:43 UTC, patronage-java-leaders-2021 requested changes

2021-06-25 13:43 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/studentrecord/dto/UserDTO.java
> +import java.util.Set;
Proszę o usunięcie nadmiarowych importów.

2021-06-25 13:43 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/studentrecord/mapper/UserMapper.java
> +                .map(userStage -> userStage.getStage().getTechnologyGroup())
W przypadku gdy `userStage.getStage()` będzie nullem wówczas mamy NPE. Dodaj proszę  `.filter()`, przed mapowaniem, który odfiltruje nulle.

2021-06-25 13:43 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/studentrecord/mapper/UserMapper.java
> +                        .status(user.getStatus().getName())
Gdy `user.getStatus()` będzie nullem mamy NPE. Proszę o poprawkę.

2021-06-25 13:43 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/studentrecord/mapper/UserMapper.java
> +                .filter(userStage -> userStage.getStage().getTechnologyGroup().equals(group))
W przypadku gdy `userStage.getStage()` będzie nullem - mamy NPE. Sprawdź proszę najpierw czy wspomniane wywołanie nie skończy się nullem, a jeśli będzie wartość wówczas możesz zrealizować aktualną implementację. Proszę o poprawkę.

2021-06-25 20:40 UTC, patronage-java-leaders-2021 approved these changes
Przed merge'm, dodaj proszę o zmianę zgodnie z informacją w komentarzu.

2021-06-25 20:40 UTC, patronage-java-leaders-2021 commented on src/main/java/com/intive/patronative/studentrecord/mapper/UserMapper.java
> +                .filter(Objects::nonNull)
Tutaj powinno być:
`.filter(userStage -> nonNull(userStage.getStage()))`
Proszę o zmianę.

2021-06-25 22:00 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/studentrecord/mapper/UserMapper.java
> +import com.intive.patronative.studentrecord.dto.EditedUserDTO;
nadmiarowy import

2021-06-25 22:10 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/studentrecord/mapper/UserMapper.java
> +                .filter(userStage -> nonNull(userStage.getStage()) && userStage.getStage().getTechnologyGroup().equals(group))
Przydało by się sprawdzić czy aby userStages nie jest null'em i czy getTechnologyGroup() nie zwróci null'a.

2021-06-25 22:26 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/studentrecord/service/UserService.java
> +        if (nonNull(user) && nonNull(user.getImage())) {
getUserFromDAtabaseByLogin() nie powinna zwrócić null'a więc nonNull raczej nie jest potrzebne.

2021-06-25 22:27 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/studentrecord/service/UserService.java
> +        if (nonNull(user)) {
tu podobnie null'a nie powinno być

2021-06-25 22:28 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/studentrecord/service/UserService.java
> +            throw new AlreadyExistsException("login", saveUserDTO.getLogin());
Jeżeli saveUserDTO będzie null'em dostaniemy wyjątek

2021-06-25 22:30 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/studentrecord/service/UserService.java
> +                new UserNotFoundException(login));
Tu możesz wykorzystać metodę getUserFromDatabaseByLogin co sprawdzi walidność loginu i rzuci za ciebie wyjątkiem.

2021-06-25 22:32 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/studentrecord/service/UserService.java
> +        return (user.getStatus() != null) && (user.getStatus().getName() != null)
Tu można by dla pewności dodać nonNull(user).

2021-06-25 22:34 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/studentrecord/service/UserService.java
> +        final var userStatus = statusRepository.findByName(saveUserDTO.getStatus());
Trzeba by sprawdzić czy saveUserDTO nie jest nullem

2021-06-25 22:36 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/studentrecord/service/UserService.java
> +                .build();
Z tego można by zrobić maper i sprawdzić czy saveUserDTO nie jest null'em.

2021-06-25 22:36 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/studentrecord/service/UserService.java
> +        return stages.stream()
Można by dodać Optional.ofNullable(stages)

2021-06-25 22:37 UTC, lzolkiewski commented on src/main/java/com/intive/patronative/studentrecord/service/UserService.java
> +        return groups.stream()
Przydałby się tu też Optional.ofNullable(groups)

2021-06-26 06:06 UTC, kari565 commented on src/main/java/com/intive/patronative/studentrecord/service/UserService.java
> +        if (nonNull(user)) {
ok

2021-06-26 06:06 UTC, kari565 commented on src/main/java/com/intive/patronative/studentrecord/service/UserService.java
> +        if (nonNull(user) && nonNull(user.getImage())) {
ok

2021-06-26 06:09 UTC, kari565 commented on src/main/java/com/intive/patronative/studentrecord/service/UserService.java
> +                new UserNotFoundException(login));
ok

2021-06-26 06:12 UTC, kari565 commented on src/main/java/com/intive/patronative/studentrecord/service/UserService.java
> +        return (user.getStatus() != null) && (user.getStatus().getName() != null)
ok

2021-06-26 06:18 UTC, kari565 commented on src/main/java/com/intive/patronative/studentrecord/service/UserService.java
> +    }
ok

2021-06-26 06:26 UTC, kari565 commented on src/main/java/com/intive/patronative/studentrecord/service/UserService.java
> +        return groups.stream()
ok

2021-06-26 06:28 UTC, kari565 commented on src/main/java/com/intive/patronative/studentrecord/service/UserService.java
> +        return stages.stream()
Dałam Optional.of().

2021-06-26 06:29 UTC, kari565 commented on src/main/java/com/intive/patronative/studentrecord/mapper/UserMapper.java
> +import com.intive.patronative.studentrecord.dto.EditedUserDTO;
ok

2021-06-26 06:29 UTC, kari565 commented on src/main/java/com/intive/patronative/studentrecord/mapper/UserMapper.java
> +                .filter(Objects::nonNull)
ok

2021-06-26 21:05 UTC, kari565 commented on src/main/java/com/intive/patronative/studentrecord/mapper/UserMapper.java
> +                .filter(userStage -> nonNull(userStage.getStage()) && userStage.getStage().getTechnologyGroup().equals(group))
ok

2021-06-26 21:05 UTC, kari565 commented on src/main/java/com/intive/patronative/studentrecord/service/UserService.java
> +            throw new AlreadyExistsException("login", saveUserDTO.getLogin());
Przy wysłaniu pustego body zostaje zwrócona odpowiedź Bad Request. Wydaje mi się, że to nie będzie nullem przy takim wykorzystaniu tej metody jakie mamy w aplikacji.

2021-06-26 21:05 UTC, kari565 commented on src/main/java/com/intive/patronative/studentrecord/service/UserService.java
> +        final var userStatus = statusRepository.findByName(saveUserDTO.getStatus());
ok, dodany mapper.

2021-06-26 21:05 UTC, kari565 commented on src/main/java/com/intive/patronative/studentrecord/service/UserService.java
> +                .build();
ok

2021-06-26 21:28 UTC, lzolkiewski approved these changes

2021-06-26 21:38 UTC, merged